name: 'On Pushes and Pulls'

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        
      - name: Get User's team bindings
        uses: tspascoal/get-user-teams-membership@v2
        id: actorTeams
        with:
          username: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Terraform init
        run: echo 'Runinng Terraform init'
      
      - name: Terraform plan
        run: echo 'Running Terraform plan'

      - name: Non Admin user requires additional policies
        if: ${{ !(contains(steps.actorTeams.outputs.teams, 'admin')) }}
        run: |
          echo 'Running OPA Policy 1 for user'
          echo 'Running OPA Policy 2 for user'

      - name: Check all params
        run: echo 'Checking results'
      
      - name: Do terraform apply if push to main
        run: echo 'Running Terraform apply'
